### ISSUE TITLE
Make the VM settings into a file

### ISSUE THREAD

**Issue by AeliusRuivus** [86Box/86BoxManager#105]
Hi there, fist of all thanks for the app, amazing addition to 86Box!
I would like to suggest that the settings for each VM should be stored in an INI file, either in the main manager application folder, or in the user's documents folder
I have two main reasons for this suggestion:
1) 86Box is portable, and this could make the manager portable as well (if we choose to store the INI in the application own directory)
2) We would be able to manually edit the name, description and patch of all VMs in a single place. Not a big deal, but since currently the settings are saved in binary in the Registry, that can be a hassle to edit/export etc.

Once again, thanks!
Ruivo

**Comment by daviunic** [comment]
Hi, thank you for your feedback. This idea (or rather a very similar one) is already partially implemented in my WIP rewrite (version 2.0), however, in the mean time a cross-platform manager has also been developed, putting the future of this one into question. I'll see how things will turn out, I might finish this one if there's enough interest, otherwise I'll probably move on.

The way I went about it is having a single vmlist.json file in appdata which lists all the VMs and their properties and is easily user-editable. The location of this file is arbitrary really, and can easily be changed to something else if it's deemed better.

**Comment by AeliusRuivus** [comment]
I haven't heard of other manager for 86Box, but I hope you don't give up on this one! If there is a tally for "enough interest", count my vote in!

**Comment by xafero** [comment]
You could try https://github.com/RetBox/86BoxManagerX/releases

**Comment by daviunic** [comment]
This is not planned currently as explained two years ago.
