### ISSUE TITLE
Existing VMs aren't relocated when the VM folder is changed in the settings

### ISSUE THREAD

**Issue by daviunic** [86Box/86BoxManager#14]
Currently, existing VMs will stay where they are and new ones will be created in the new folder. The VM folder should instead just be renamed/moved and every VM's path variable updated so that all VMs are kept in one place.

Confirmed in 1.0.3. Since I'll implement this as part of an optional action (yes-no message box…), this has been pushed back to 1.1.

**Comment by Xeon3D** [comment]
I don't really see this as a bug. If you change the path on any other virtualization software, VMs in the old path are not relocated automagically...

**Comment by daviunic** [comment]
Will be added as an option after you change the VMs folder in the form of a yes-no messagebox.

**Comment by Xeon3D** [comment]
Yes. I might've expressed myself badly since English is not my mother
language.

I'm all for giving the users choice (and that was the topic of a light
discussion I have had with obattler and 86box before). All I meant was I
don't see giving the users that choice as bug but an improvement.

A terça, 23/10/2018, 06:02, David Simunič <notifications@github.com>
escreveu:

**Comment by daviunic** [comment]
Version 2.0 allows each VM to have its own unique path, which partially covers this issue. Will see if there'll be any changes to the relocation code.
