### ISSUE TITLE
[Feature] Portable mode

### ISSUE THREAD

**Issue by mgtroyas** [86Box/86BoxManager#93]
Hello,

First of all thank you very much for the work on this great frontend.

I have my 86box install on a NAS, with several VMs configured. When I tried to run the Manager from my laptod I'm welcomed by the initial setup, and all the VMs are gone.

Does the Manager save it's config on the windows registry, or the user profile?

In that case I suggest giving an option to run it on portable mode, saving the settings on a file alongside the executable. It'll be useful also for people having 86box on an external USB drive.

**Comment by daviunic** [comment]
Hi, I'm the original developer of this program. Be aware that 86Box Manager is no longer actively maintained by me, as I'm no longer affiliated with the 86Box project in any official capacity. But I can still answer your question.

The list of VMs and their metadata is stored in the current user's registry key (HKCU). Even if you manually configure your VM folders outside of 86Box Manager, they still need to be added (imported) into the Manager if you wish to manage them there - the relevant registry keys and values are created when you do this. And running 86Box Manager on a different account or computer of course means that your VM list isn't transfered over due to the nature of how HKCU (and the registry as a whole) works. You need to add all the VMs again in that case.

As for your idea: like I said at the start, I no longer work on this program, and I'm not sure what the developers of 86Box have in plans for VM management in the future. However, I think it's unlikely there will be any major updates made to this program in the foreseeable the future. It's a good idea, though. One that I once planned to implement as part of a larger rewrite of this program (version 2.0), but that never happened and probably never will.

**Comment by mgtroyas** [comment]
Understood, thank you very much anyway for the answer and all your work.

**Comment by marek-sezemsky** [comment]
@daviunic hi David, I wonder - is there a 2.0 branch available somewhere? Even if it would be work-in-progress...

**Comment by daviunic** [comment]
It's work in progress to the point it's not in a working state yet. For now the repo is on my account, might transfer it to the 86Box org later if the team agrees.

**Comment by Ohrwerk** [comment]
> The list of VMs and their metadata is stored in the current user's registry key (HKCU). ....


This list is stored as binary value under "HKEY_CURRENT_USER\Software\86Box\Virtual Machines".
It took some time to find this value, because I searched for 86Manager and not for 86Box.
This binary value does not make it easy to change paths.
So far I have not found a way to change my paths there.
The only way left is to delete the machine and recreate it.
I would prefer an ini file more.
If there should be an updated version, it would be nice if they could change this.
The manager makes it much easier to use 86Box.
Thank you

**Comment by daviunic** [comment]
The registry layout is explained on the wiki page "Registry keys and values" on this repo. https://github.com/86Box/86BoxManager/wiki/Registry-keys-and-values

VM path is not individually configurable in version 1.x, your VMs are always created in the directory you set in the program settings.

I am working on version 2.0 which will store the VM list in a JSON file and will allow you to change the location of each VM individually as well, making relocations easier.

**Comment by marek-sezemsky** [comment]
> I am working on version 2.0 which will store the VM list in a JSON file and will allow you to change the location of each VM individually as well, making relocations easier.

Is there a branch..?

**Comment by Ohrwerk** [comment]
Thank you daviunic

**Comment by daviunic** [comment]
> > I am working on version 2.0 which will store the VM list in a JSON file and will allow you to change the location of each VM individually as well, making relocations easier.
> 
> Is there a branch for this?

There's a new repo for it: https://github.com/daviunic/86BM2/

It's not in a usable state yet.
